### ISSUE TITLE
CSS standard notation

### ISSUE THREAD

**Issue by diegolanda** [nearshorecode/web-ui#2]
We have 2 proposals:

Should we go with:

`wui-stack` all minus

or

`wuiStack` camelCased

**Comment by Taxxx** [comment]
all minus

**Comment by m-camacho** [comment]
My two cents: `wui-stack`
I would suggest to use kebab-case team 👍

**Comment by diegolanda** [comment]
@nearshorecode/website  

We need to update custom styles to `kebab-case` Free to pick :)

**Comment by m-camacho** [comment]
Closing this one due to https://github.com/nearshorecode/web-ui/pull/36
